# -*- coding: utf-8 -*-
"""Fraud_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpVVok-xlJoIuBP-Ibs1lj9WzRpl9g8U
"""

import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Model
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# Load Dataset
df = pd.read_csv("/content/fraud_detection_dataset.csv")

# Display First 5 Rows
print(df.head())

# Dataset Information
print(df.info())

# Check Missing Values
print(df.isnull().sum())

# Encode Categorical Columns
le = LabelEncoder()

df["Location"] = le.fit_transform(df["Location"])
df["Merchant"] = le.fit_transform(df["Merchant"])
df["DeviceType"] = le.fit_transform(df["DeviceType"])

# Features and Target
X = df.drop(["Fraud", "TransactionID"], axis=1)

y = df["Fraud"]

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train Model
model = RandomForestClassifier()

model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)

# Classification Report
print("\nClassification Report:\n")

print(classification_report(y_test, y_pred))

# Fraud Count Visualization
sns.countplot(x=df["Fraud"])

plt.title("Fraud vs Non-Fraud Transactions")

plt.xlabel("Fraud")

plt.ylabel("Count")

plt.show()

# Predict New Transaction
# Format:
# [Amount, Time, Location, Merchant, DeviceType]

new_transaction = [[75000, 2, 1, 4, 0]]

prediction = model.predict(new_transaction)

if prediction[0] == 1:
    print("\nFraud Transaction Detected")
else:
    print("\nLegitimate Transaction")